Disabling VPN (ipsec) for MFW in EOS
untangle/mfw_feeds pull request #187
Opened 2023-09-06 17:53 UTC by amruth17

ipsec process would start automatically when the BST container comes up 

-bash-4.2# ps -ef | grep ipsec
3072 root      1792 S    /usr/lib/ipsec/starter --daemon charon --nofork
3128 root      5492 S    /usr/lib/ipsec/charon
-bash-4.2#

Disabling Ipsec process for ipsec.init for EOS-MFW platform 

AFTER change:

-bash-4.2# ps -ef | grep ipsec
root      3575     2  0 10:36 ?        00:00:00 [ipsec_inline_in]
root      3576     2  0 10:36 ?        00:00:00 [ipsec_inline_mb]
root      3577     2  0 10:36 ?        00:00:00 [ipsec_inline_sb]
root      3578     2  0 10:36 ?        00:00:00 [ipsec_inline_vf]
root     13856 13644  0 10:38 pts/3    00:00:00 grep --color=auto ipsec
-bash-4.2#

2023-09-08 14:41 UTC, karthiksridhar25 commented on strongswan-full/files/override.ipsec.init
> +platform=`cat /proc/cmdline  | xargs -n1 |grep platform |cut -d '=' -f2`
Can we use awk instead of cat here

2023-09-08 15:08 UTC, amruth17 commented on strongswan-full/files/override.ipsec.init
> +platform=`cat /proc/cmdline  | xargs -n1 |grep platform |cut -d '=' -f2`
actually similar code is present in SfeDisable script inside mfw-in-eos repo , they are using "cat" cmd itself , hence used the same thing here as well ? 

Any advantage of using awk over cat here ?

2023-09-08 15:17 UTC, karthiksridhar25 commented on strongswan-full/files/override.ipsec.init
> +platform=`cat /proc/cmdline  | xargs -n1 |grep platform |cut -d '=' -f2`
Yeah awk is generally more efficient than cat . considered better practice than using cat

2023-09-08 16:32 UTC, amruth17 commented on strongswan-full/files/override.ipsec.init
> +platform=`cat /proc/cmdline  | xargs -n1 |grep platform |cut -d '=' -f2`
Thanks , will make that change

2023-09-13 18:12 UTC, amruth17 commented on strongswan-full/files/override.ipsec.init
> +	fi
@jsommerville-untangle and @iramasamy , is this implementation okay ? or do we need a script that gets invoked from the Control agent ?

2023-09-14 18:07 UTC, karthiksridhar25 commented on strongswan-full/files/override.ipsec.init
> +	fi
@amruth17 Discussed with john, you can proceed with your changes for now

2023-09-14 18:07 UTC, karthiksridhar25 approved these changes

2023-09-14 19:41 UTC, jsommerville-untangle requested changes
i think we can just close this PR - this is unnecessary at this time

2023-10-09 19:21 UTC, closed without merging